# Generated by Django 4.2 on 2023-04-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parse", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="img",
            field=models.ImageField(upload_to="parse/images/"),
        ),
    ]
