# Generated by Django 4.2 on 2023-04-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parse", "0002_alter_data_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="parse/images/"),
        ),
    ]
