# Generated by Django 4.2 on 2023-04-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parse", "0003_alter_data_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="data",
            name="img_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="data",
            name="text",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="data",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
